---
abstract: 'Catalyst based application'
author:
  - 'Catalyst developer'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PF2K7
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0.14
  Catalyst::Engine::PSGI: 0.11
  Catalyst::Plugin::ConfigLoader: 0.30
  Catalyst::Plugin::Static::Simple: 0.29
  Catalyst::Runtime: 5.80028
  Config::General: 2.50
  YAML::LibYAML: 0.34
  HTML::FormHandler: 0.32005
  Moose: 1.21
  namespace::autoclean: 0.11
  MooseX::Types::Common::String: 0.001002 
resources:
  license: http://dev.perl.org/licenses/
version: 0.1.0
