#!/bin/sh

perl script/pf2k7_create.pl model PF2K7 DBIC::Schema PF2K7::Schema \
     create=static components=TimeStamp,EncodedColumn              \
     dbi:SQLite:db/pf.db                                           \
     on_connect_do="PRAGMA foreign_keys = ON"
perl -Ilib utils/make_sql
