package PF2K7::Model::PF2K7;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PF2K7::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db/pf.db',
        user => '',
        password => '',
    }
);

=head1 NAME

PF2K7::Model::PF2K7 - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PF2K7>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PF2K7::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Paul Johnson

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
